services:
  test: &defaults
    build:
      context: .
      target: base
    working_dir: /app
    command: go test -v ./...
    env_file:
      - ./.docker/test.env
    volumes:
      - .:/app
    depends_on:
      - mysql_test
  app:
    <<: *defaults
    command: go run ./main.go serve
    ports:
      - "8080:80"
    env_file:
      - ./.docker/dev.env
    depends_on:
      - mysql
  ci:
    <<: *defaults
    build: 
      context: .
      target: ci
    volumes: []
  mysql: &mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.docker/dev.env
    volumes:
        - ./.docker/init.sql:/docker-entrypoint-initdb.d/init.sql
  mysql_test:
    <<: *mysql
    env_file:
      - ./.docker/test.env
    